print(10 == 10)
print(10 != 5)
print(5 > 10)
print(18 >= 18)
print(10 + 5)
print(10 > 5)
print(bool("Python"))
print(10 == 20)
age = 20
print(age >= 18)
print(True and True)
print(True and False)
print(False and True)
print(False and False)
print(True or True)
print(True or False)
print(False or True)
print(False or False)
print(not True)
print(not False)
age = 25

print(age >= 18 and age <= 60)
age = 20

print(not age < 18)
print(bool(0))
print(bool(1))
print(bool(-5))
print(bool(""))
print(bool("Python"))
print(bool(False))
print((True))
print((None))
print(bool(0),type(0))
print(bool(1),type(1))
print(bool(-5),type(-5))
print(bool(""),type(""))
print(bool("Python"),type("Python"))
print(bool(False),type(False))
print(bool(None),type(None))